[package]
name = "hspee/food-truck"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Network = "rofishy/network@0.1.2"
Janitor = "howmanysmall/janitor@1.17.0"
Promise = "evaera/promise@4.0.0"
cmdr = "evaera/cmdr@1.12.0"
Fusion = "elttob/fusion@0.3.0"